services:
  botDiscordCheckerProdDB:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5434:5432
    volumes:
      - botDiscordCheckerProdDB:/var/lib/postgresql/data
    networks:
      - prodNetwork

  server:
    depends_on:
      botDiscordCheckerProdDB:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}
      - DISCORD_PUBLIC_KEY=${DISCORD_PUBLIC_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - HANDLE_DOMAINS_ALERT_SPEED=${HANDLE_DOMAINS_ALERT_SPEED}
      - DISCORD_NOTIFICATION_CHANNEL_ID=${DISCORD_NOTIFICATION_CHANNEL_ID}
    image: arnaudlyard/bot-discord
    networks:
      - prodNetwork

volumes:
  botDiscordCheckerProdDB:

networks:
  prodNetwork:
